"""add_email_verification_fields_to_user

Revision ID: 206f78d2d2a0
Revises: 240401dad61c
Create Date: 2026-08-31 16:29:34.616721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206f78d2d2a0'
down_revision: Union[str, None] = '240401dad61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add nullable fields first
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_code_expiry', sa.DateTime(), nullable=True))
    
    # Add is_verified as nullable first for safety
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE users SET is_verified = FALSE WHERE is_verified IS NULL")
    
    # Make is_verified non-nullable
    op.alter_column('users', 'is_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code_expiry')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
