"""add_is_active_field_to_client

Revision ID: 0ff934efac1a
Revises: 4459e6a92619
Create Date: 2026-09-26 15:07:00.146520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff934efac1a'
down_revision: Union[str, None] = '4459e6a92619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    
    # Update existing rows and make column NOT NULL
    op.execute("UPDATE clients SET is_active = true WHERE is_active IS NULL")
    op.alter_column('clients', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
