"""reverse_user_domain_relationships

Revision ID: 9c36ac9dd1df
Revises: 286b775e551b
Create Date: 2026-08-13 10:43:59.581591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c36ac9dd1df'
down_revision: Union[str, None] = '286b775e551b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_id columns as nullable first (for existing tables)
    op.add_column('barbers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Create foreign keys
    op.create_foreign_key('barbers_user_id_fkey', 'barbers', 'users', ['user_id'], ['id'])
    op.create_foreign_key('clients_user_id_fkey', 'clients', 'users', ['user_id'], ['id'])
    
    # Since tables are empty, we can now make columns non-nullable
    op.alter_column('barbers', 'user_id', nullable=False)
    op.alter_column('clients', 'user_id', nullable=False)
    
    # Remove old foreign keys and columns from users table
    op.drop_constraint('users_client_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_barber_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    op.drop_column('users', 'barber_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back old columns to users
    op.add_column('users', sa.Column('barber_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Create old foreign keys
    op.create_foreign_key('users_barber_id_fkey', 'users', 'barbers', ['barber_id'], ['id'])
    op.create_foreign_key('users_client_id_fkey', 'users', 'clients', ['client_id'], ['id'])
    
    # Drop new foreign keys and columns
    op.drop_constraint('barbers_user_id_fkey', 'barbers', type_='foreignkey')
    op.drop_column('barbers', 'user_id')
    op.drop_constraint('clients_user_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
