"""add_is_active_field_to_barber

Revision ID: cad3712d8097
Revises: 0ff934efac1a
Create Date: 2026-09-28 09:11:40.931302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad3712d8097'
down_revision: Union[str, None] = '0ff934efac1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    
    # Update existing rows and make column NOT NULL
    op.execute("UPDATE barbers SET is_active = true WHERE is_active IS NULL")
    op.alter_column('barbers', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barbers', 'is_active')
    # ### end Alembic commands ###
