"""update_working_hours_lunch_break_fields

Revision ID: 4459e6a92619
Revises: 78e467b2e893
Create Date: 2026-09-15 17:01:34.759585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4459e6a92619'
down_revision: Union[str, None] = '78e467b2e893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_hours', sa.Column('lunch_break_start', sa.Time(), nullable=True))
    op.add_column('working_hours', sa.Column('lunch_break_end', sa.Time(), nullable=True))
    op.drop_column('working_hours', 'lunch_break')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_hours', sa.Column('lunch_break', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('working_hours', 'lunch_break_end')
    op.drop_column('working_hours', 'lunch_break_start')
    # ### end Alembic commands ###
