"""add_is_active_fields_to_shop_barber_service

Revision ID: 78e467b2e893
Revises: 206f78d2d2a0
Create Date: 2026-09-09 13:05:17.342752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e467b2e893'
down_revision: Union[str, None] = '206f78d2d2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('services', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('shops', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    
    # Update existing rows and make columns NOT NULL
    op.execute("UPDATE barbers SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE services SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE shops SET is_active = true WHERE is_active IS NULL")
    
    op.alter_column('barbers', 'is_active', nullable=False)
    op.alter_column('services', 'is_active', nullable=False)
    op.alter_column('shops', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'is_active')
    op.drop_column('services', 'is_active')
    op.drop_column('barbers', 'is_active')
    # ### end Alembic commands ###
