"""make is_owner not nullable

Revision ID: c56128a3ad32
Revises: 620f2c1ff17f
Create Date: 2026-08-05 07:26:24.092539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56128a3ad32'
down_revision: Union[str, None] = '620f2c1ff17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('barbers', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('barbers', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
