"""add_location_and_accepting_new_barbers_to_shop

Revision ID: 240401dad61c
Revises: 9c36ac9dd1df
Create Date: 2026-08-30 08:09:05.323743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240401dad61c'
down_revision: Union[str, None] = '9c36ac9dd1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add location column as nullable first for consistency
    op.add_column('shops', sa.Column('location', sa.String(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE shops SET location = 'Unknown' WHERE location IS NULL")
    
    # Make location column non-nullable
    op.alter_column('shops', 'location', nullable=False)
    
    # Add accepting_new_barbers as nullable first for safety
    op.add_column('shops', sa.Column('accepting_new_barbers', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE shops SET accepting_new_barbers = TRUE WHERE accepting_new_barbers IS NULL")
    
    # Make column non-nullable
    op.alter_column('shops', 'accepting_new_barbers', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'accepting_new_barbers')
    op.drop_column('shops', 'location')
    # ### end Alembic commands ###
